[package]
name    = "sd-desktop-linux"
version = "0.1.0"

edition.workspace    = true
license.workspace    = true
repository.workspace = true

[dependencies]
libc  = { workspace = true }
tokio = { workspace = true, features = ["fs"] }

[target.'cfg(target_os = "linux")'.dependencies]
wgpu = { version = "22.1", default-features = false }
# WARNING: gtk should follow the same version used by tauri
# https://github.com/tauri-apps/tauri/blob/tauri-v2.0.0/crates/tauri/Cargo.toml#L100
gtk = { version = "0.18", features = ["v3_24"] }
