[package]
name    = "sd-core-sync"
version = "0.0.0"

edition = "2021"

[features]
default = []

[dependencies]
# Spacedrive Sub-crates
sd-core-prisma-helpers = { path = "../prisma-helpers" }

sd-actors = { path = "../../../crates/actors" }
sd-prisma = { path = "../../../crates/prisma" }
sd-sync   = { path = "../../../crates/sync" }
sd-utils  = { path = "../../../crates/utils" }

# Workspace dependencies
async-channel       = { workspace = true }
async-stream        = { workspace = true }
chrono              = { workspace = true }
futures             = { workspace = true }
futures-concurrency = { workspace = true }
itertools           = { workspace = true }
prisma-client-rust  = { workspace = true, features = ["rspc"] }
rmp-serde           = { workspace = true }
rmpv                = { workspace = true }
rspc                = { workspace = true }
serde               = { workspace = true }
thiserror           = { workspace = true }
tokio               = { workspace = true }
tracing             = { workspace = true }
uhlc                = { workspace = true }
uuid                = { workspace = true }

[dev-dependencies]
tracing-subscriber = { workspace = true, features = ["env-filter"] }
tracing-test       = { workspace = true }
