[package]
name    = "sd-p2p-tunnel"
version = "0.1.0"

authors              = ["Oscar Beaumont <oscar@otbeaumont.me>"]
edition.workspace    = true
license.workspace    = true
repository.workspace = true

[dependencies]
# Spacedrive Sub-crates
sd-p2p       = { path = "../../" }
sd-p2p-proto = { path = "../proto" }

# Workspace dependencies
thiserror = { workspace = true }
tokio     = { workspace = true, features = ["io-util"] }
