[package]
name    = "sd-task-system"
version = "0.1.0"

authors                = ["Ericson Soares <ericson@spacedrive.com>"]
edition.workspace      = true
license.workspace      = true
repository.workspace   = true
rust-version.workspace = true

[dependencies]
# Workspace deps
async-channel       = { workspace = true }
async-trait         = { workspace = true }
futures             = { workspace = true }
futures-concurrency = { workspace = true }
pin-project-lite    = { workspace = true }
thiserror           = { workspace = true }
tokio               = { workspace = true, features = ["parking_lot", "rt-multi-thread", "sync", "time"] }
tokio-stream        = { workspace = true }
tracing             = { workspace = true }
uuid                = { workspace = true, features = ["v4"] }

# Specific Task System dependencies
downcast-rs = "1.2"

[dev-dependencies]
lending-stream     = { workspace = true }
rand               = { workspace = true }
rmp-serde          = { workspace = true }
serde              = { workspace = true, features = ["derive"] }
tempfile           = { workspace = true }
thiserror          = { workspace = true }
tokio              = { workspace = true, features = ["fs", "macros", "test-util"] }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
tracing-test       = { workspace = true, features = ["no-env-filter"] }
uuid               = { workspace = true, features = ["serde"] }
