[package]
name    = "sd-desktop-windows"
version = "0.1.0"

edition.workspace    = true
license.workspace    = true
repository.workspace = true

[dependencies]
libc     = { workspace = true }
normpath = { workspace = true }

[target.'cfg(target_os = "windows")'.dependencies.windows]
features = ["Win32_Foundation", "Win32_System_Com", "Win32_UI_Shell"]
version  = "0.58"
