[package]
name    = "sd-sync"
version = "0.1.0"

edition.workspace    = true
license.workspace    = true
repository.workspace = true

[dependencies]
prisma-client-rust = { workspace = true }
rmp                = { workspace = true }
rmp-serde          = { workspace = true }
rmpv               = { workspace = true }
serde              = { workspace = true }
uhlc               = { workspace = true }
uuid               = { workspace = true, features = ["serde", "v7"] }
