[package]
name    = "sd-core-indexer-rules"
version = "0.1.0"

authors              = ["Ericson Soares <ericson@spacedrive.com>", "Vítor Vasconcellos <vitor@spacedrive.com>"]
edition.workspace    = true
license.workspace    = true
repository.workspace = true

[dependencies]
# Spacedrive Sub-crates
sd-prisma = { path = "../../../crates/prisma" }
sd-utils  = { path = "../../../crates/utils" }

# Workspace dependencies
chrono              = { workspace = true }
futures-concurrency = { workspace = true }
globset             = { workspace = true, features = ["serde1"] }
prisma-client-rust  = { workspace = true }
rmp-serde           = { workspace = true }
rspc                = { workspace = true }
serde               = { workspace = true, features = ["derive", "rc"] }
specta              = { workspace = true }
thiserror           = { workspace = true }
tokio               = { workspace = true, features = ["fs"] }
tracing             = { workspace = true }
uuid                = { workspace = true, features = ["serde", "v4"] }

# Specific Indexer Rules dependencies
gix-ignore = { version = "0.11.2", features = ["serde"] }

[dev-dependencies]
tempfile = { workspace = true }
