[package]
name    = "sd-prisma"
version = "0.1.0"

edition = "2021"

[dependencies]
# Spacedrive Sub-crates
sd-sync = { path = "../sync" }

# Workspace dependencies
prisma-client-rust = { workspace = true }
rmp-serde          = { workspace = true }
rmpv               = { workspace = true }
serde              = { workspace = true }
uuid               = { workspace = true }
