[package]
name    = "sd-mobile-ios"
version = "0.1.0"

edition.workspace      = true
license.workspace      = true
repository.workspace   = true
rust-version.workspace = true

[lib]
# iOS requires static linking
# Makes sense considering this lib needs to link against call_resolve and get_data_directory,
# which are only available when linking against the app's ObjC
crate-type = ["staticlib"]

[target.'cfg(target_os = "ios")'.dependencies]
# Spacedrive Sub-crates
sd-mobile-core = { path = "../../core" }
