[package]
name    = "sd-mobile-android"
version = "0.1.0"

edition.workspace      = true
license.workspace      = true
repository.workspace   = true
rust-version.workspace = true

[lib]
# Android can use dynamic linking since all FFI is done via JNI
crate-type = ["cdylib"]

[target.'cfg(target_os = "android")'.dependencies]
# Spacedrive Sub-crates
sd-mobile-core = { path = "../../core" }

# Workspace dependencies
tracing = { workspace = true }

# Specific Mobile Android dependencies
jni = "0.21.1"
