[package]
name    = "sd-sync-generator"
version = "0.1.0"

edition.workspace    = true
license.workspace    = true
repository.workspace = true

[dependencies]
# Workspace dependencies
prisma-client-rust-sdk = { workspace = true }
serde                  = { workspace = true, features = ["derive"] }
thiserror              = { workspace = true }

# Specific Sync Generator dependencies
nom = "7.1"
