[package]
name    = "sd-core-file-path-helper"
version = "0.1.0"

authors                = ["Ericson Soares <ericson@spacedrive.com>"]
edition.workspace      = true
license.workspace      = true
readme                 = "README.md"
repository.workspace   = true
rust-version.workspace = true

[dependencies]
# Inner Core Sub-crates
sd-core-prisma-helpers = { path = "../prisma-helpers" }
sd-core-sync           = { path = "../sync" }

# Spacedrive Sub-crates
sd-prisma = { path = "../../../crates/prisma" }
sd-utils  = { path = "../../../crates/utils" }

# Workspace dependencies
chrono             = { workspace = true, features = ["serde"] }
prisma-client-rust = { workspace = true }
regex              = { workspace = true }
serde              = { workspace = true, features = ["derive"] }
thiserror          = { workspace = true }
tokio              = { workspace = true, features = ["fs"] }
tracing            = { workspace = true }

# Specific File Path Helper dependencies
[target.'cfg(target_os = "windows")'.dependencies.windows]
features = ["Win32_Security", "Win32_Storage_FileSystem"]
version  = "0.58"
